default:
  tags: [shared-fi]

variables:
  DOCUMENTATION_NAME: "docs.pdf"
  ARCHIVE_NAME: "dist.tar.gz"
  PACKAGE_NAME: "fiquill"

workflow:
  rules:
    - if: $CI_COMMIT_TAG

compile docs:
  image: 123marvin123/typst:0.13.1
  artifacts:
    when: on_success
    paths: ["{$DOCUMENTATION_NAME}"]
  script:
    - typst compile docs/docs.typ ${DOCUMENTATION_NAME} --root .

build package:
  image: bash
  artifacts:
    when: on_success
    paths: ["${ARCHIVE_NAME}"]
  script:
    - mkdir ${CI_COMMIT_TAG}
    - cp -r src assets LICENSE README.md typst.toml ${CI_COMMIT_TAG}
    - tar cvzf ${ARCHIVE_NAME} ${CI_COMMIT_TAG}

publish package:
  image: curlimages/curl:latest
  needs: ["build package", "compile docs"]
  script:
    - |
      curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file ${ARCHIVE_NAME} \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${CI_COMMIT_TAG}/${ARCHIVE_NAME}"
    - |
      curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file ${DOCUMENTATION_NAME} \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${CI_COMMIT_TAG}/${DOCUMENTATION_NAME}"
