[package]
name = "ctu-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Samuel Stanek", "Ivan Kushpel"]
license = "BSD-3-Clause"
description = "A template for writing theses at Czech Technical University in Typst."

[template]
path = "example"
entrypoint = "thesis.typ"
